language: python

python:
  - "3.5"

env:
  - TOXENV=py27-d19
  - TOXENV=py27-d110

  - TOXENV=py35-d19
  - TOXENV=py35-d110

before_install:
  - pip install codecov

install:
  - pip install tox "coverage<4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e $TOXENV -- py.test tests -vv --capture=no --cov=dynamicfields --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls
  - codecov
