# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 08:49
from __future__ import unicode_literals

import django.db.models.deletion
import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_dynamicfields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', picklefield.fields.PickledObjectField(editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamicfields.CustomFieldDefs')),
            ],
        ),
    ]
