# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 08:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import strategy_field.fields

import django_dynamicfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('field_type', strategy_field.fields.StrategyClassField()),
                ('init_string', models.CharField(blank=True, max_length=1000, null=True, validators=[django_dynamicfields.models.validate_json])),
                ('default_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
